name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - develop

jobs:
  aot:
    if: contains(github.ref, 'develop') || contains(github.ref, 'master')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run create:env:prod
      env:
        ASSET_CDN_HOST: ${{ secrets.ASSET_CDN_HOST }}
        COCKPIT_API_URL: ${{ secrets.COCKPIT_API_URL }}
        COCKPIT_API_KEY: ${{ secrets.COCKPIT_API_KEY }}
        GRAPHQL_HOST_URL: ${{ secrets.GRAPHQL_HOST_URL }}
        GTM_ID: ${{ secrets.GTM_ID }}
        GCP_KEY: ${{ secrets.GCP_KEY }}
        GCP_STATIC_MAPS_SECRET: ${{ secrets.GCP_STATIC_MAPS_SECRET }}
        SLACK_ERROR_HOOK_URL: ${{ secrets.SLACK_ERROR_HOOK_URL }}
    - run: npm run production

  beta:
    if: contains(github.ref, 'develop')
    needs: [aot]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "Deploy ${{github.ref}} to beta ..."
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
        DEPLOY_ROOT: ${{ secrets.DEPLOY_ROOT }}

  production:
    if: contains(github.ref, 'master')
    needs: [aot]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "Deploy ${{github.ref}} to productions ..."
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
        DEPLOY_ROOT: ${{ secrets.DEPLOY_ROOT }}
